### PR TITLE
PRIM-168: Add Notes feature

### PR DESCRIPTION
**Pull request by JackMiszencin**
Added in content about the new Add Notes feature in v1.6. Once this is merged, we may want to put in a v1.6 tag before adding content about v1.7.

### CODE REVIEW

**Comment by IanLawrence** [comment]
Can I merge this and tag as v1.6?

**Review by IanLawrence — APPROVED** [review]

**Comment by JackMiszencin** [comment]
@IanLawrence , yes, sorry for the late response. Please do.

**Comment by JackMiszencin** [comment]
And when you do, it may be useful to create a version branch once you've tagged: maint_1.6. The other PR I have on this repo should only be merged in after the creation of the 1.6 tag and version branch, since it is a v1.7 feature.

**Comment by IanLawrence** [comment]
I tagged the release. There is already a v1-7-updates branch

**Pull request merged**
